### ISSUE TITLE
Incorrect results with some negative multiples when base is a list.

### ISSUE THREAD

**Issue by atadams** [modularscale/modularscale-sass#33] opened 2012-10-11 18:39 UTC
I believe 2c23acf00768b7abd8a228f5e786c60642032394 introduced an error with certain negative multiples when the base is a list. 

Example `ms(-2, 16px 44px, 1.618, false);` should equal 9.88875px (see [ModularScale.com](http://modularscale.com/scale/?px1=16&px2=44&ra1=1.618&ra2=0)) but equals 6.11171px.

Actually the multiples -2, -3, and -4 with these settings all equal 6.11171px.

**Comment by ghandrick** [comment] 2013-02-14 17:44
Can confirm problem.

**Comment by scottkellum** [comment] 2013-02-14 18:13
The issue is confirmed, just very difficult to fix.

**Comment by scottkellum** [comment] 2013-12-30 05:12
[Should be fixed in 2.0](https://github.com/Team-Sass/modular-scale/blob/2.x/readme.md). Please reopen if it isn’t.

**Closed as completed by scottkellum** 2013-12-30 05:12 UTC
