### ISSUE TITLE
modularscale.com & www.modularscale.com are redirecting to separate websites

### ISSUE THREAD

**Issue by jLouzado** [modularscale/modularscale-sass#170] opened 2021-01-13 06:47 UTC
Hello,

This is what I'm seeing at the www:

![image](https://user-images.githubusercontent.com/2016685/104416107-34da2180-5599-11eb-99c9-bb2bd3bccdfb.png)

and at the bare domain:

![image](https://user-images.githubusercontent.com/2016685/104416163-52a78680-5599-11eb-979b-cfee19d62567.png)

**Comment by jLouzado** [comment] 2021-01-14 08:48
oh wow, they even go to the trouble of making fake books and generating fake comments 😓 

![image](https://user-images.githubusercontent.com/2016685/104566157-442d9d80-5673-11eb-918c-c448cbbb8e42.png)

complete with fake customer support and lampshading what they're doing

![image](https://user-images.githubusercontent.com/2016685/104566229-57d90400-5673-11eb-8a1e-2eab34a8b32e.png)

**Comment by scottkellum** [comment] 2021-01-19 23:31
@tbrown 👆

**Comment by scottkellum** [comment] 2021-05-26 20:02
Dupe of #167

**Closed as completed by scottkellum** 2021-05-26 20:02 UTC
