### ISSUE TITLE
ms-generate-list is returning some mixed through results

### ISSUE THREAD

**Issue by rpkoller** [modularscale/modularscale-sass#70] opened 2014-01-04 18:57 UTC
This might be related to: https://github.com/Team-Sass/modular-scale/issues/69

If i try the following on ms-generate-list (alpha 4): 

```
$ms-base: 20px 44px;
$ms-ratio: $golden $fifth;
$modDANG: ms-generate-list(12, $ms-base, $ms-ratio);
p {
    &:after{
        content:"#{$modDANG}";
    }
}
```

The results look a bit odd: 

```
p:after {
  content: "20px 32.36068px 52.36068px 84.72136px 137.08204px 221.80341px 358.88545px 580.68887px 939.57433px 1520.26321px 2459.83756px 3980.1008px 6439.93842px, 27.1935px 71.1935px 115.1935px 186.38699px 301.58049px 487.96749px 789.548px 1277.5155px 2067.06352px 3344.57906px 5411.64263px, 20px 30px 45px 67.5px 101.25px 151.875px 227.8125px 341.71875px 512.57813px 768.86719px 1153.30078px 1729.95117px 2594.92676px, 29.33333px 66px 99px 148.5px 222.75px 334.125px 501.1875px 751.78125px 1127.67188px 1691.50781px 2537.26172px"; }
```

The values are first rising for the first scale then break down and rise again. maybe the scale values are not properly sorted and also not merged with the values of the second scale in the next step?

**Comment by scottkellum** [comment] 2014-01-04 21:42
dupe of #69

**Closed as completed by scottkellum** 2014-01-04 21:42 UTC

**Comment by scottkellum** [comment] 2014-01-04 23:12
Reading this again, `ms-generate-list` is not a user-facing function. That output is correct. You should be using `ms-list` instead.

`ms-generate-list` is the raw list of possibilities and has not gone through the sorting process yet.

**Comment by rpkoller** [comment] 2014-01-05 11:32
ups ok! sorry...
